#ifndef H_WORLDGEN_NOTCHIAN_DEFAULTS
#define H_WORLDGEN_NOTCHIAN_DEFAULTS

// Auto-generated from Notchian worldgen JSON data.
// Source: notchian/generated/data/minecraft/worldgen
// Regenerate with: make worldgen-sync-defaults
// Derived from: noise_settings/overworld (min_y=-64, height=384, top_y=319)

#define WORLDGEN_DESERT_CACTUS_FLOWER_CHANCE 16
#define WORLDGEN_DESERT_DEAD_BUSH_CHANCE 2
#define WORLDGEN_HEIGHT_CAP 255
#define WORLDGEN_PLAINS_FLOWER_CHANCE 1
#define WORLDGEN_PLAINS_GRASS_CHANCE 7
#define WORLDGEN_PLAINS_MUSHROOM_CHANCE 1
#define WORLDGEN_PLAINS_PUMPKIN_CHANCE 1
#define WORLDGEN_PLAINS_TREE_BASE_CHANCE 3
#define WORLDGEN_PLAINS_TREE_PATCH_BONUS 1
#define WORLDGEN_SNOWY_GRASS_CHANCE 1
#define WORLDGEN_SNOWY_MUSHROOM_CHANCE 1
#define WORLDGEN_SNOWY_TREE_BASE_CHANCE 6
#define WORLDGEN_SWAMP_GRASS_CHANCE 5
#define WORLDGEN_SWAMP_MUSHROOM_CHANCE 1
#define WORLDGEN_SWAMP_TREE_BASE_CHANCE 255
#define WORLDGEN_SWAMP_TREE_PATCH_BONUS 127

#endif
